name = "amithshettya-github-io"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[build]
command = "deno task build"

[assets]
directory = "./public"

[[rules]]
type = "Text"
globs = ["**/*.html"]
