/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as BlogRouteImport } from "./routes/blog"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BlogCategoryRouteImport } from "./routes/blog.$category"
import { Route as BlogCategorySlugRouteImport } from "./routes/blog.$category.$slug"

const BlogRoute = BlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryRoute = BlogCategoryRouteImport.update({
  id: "/$category",
  path: "/$category",
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => BlogCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/blog": typeof BlogRouteWithChildren
  "/blog/$category": typeof BlogCategoryRouteWithChildren
  "/blog/$category/$slug": typeof BlogCategorySlugRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/blog": typeof BlogRouteWithChildren
  "/blog/$category": typeof BlogCategoryRouteWithChildren
  "/blog/$category/$slug": typeof BlogCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/blog": typeof BlogRouteWithChildren
  "/blog/$category": typeof BlogCategoryRouteWithChildren
  "/blog/$category/$slug": typeof BlogCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    "/" | "/about" | "/blog" | "/blog/$category" | "/blog/$category/$slug"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/blog" | "/blog/$category" | "/blog/$category/$slug"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/blog"
    | "/blog/$category"
    | "/blog/$category/$slug"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/blog": {
      id: "/blog"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/blog/$category": {
      id: "/blog/$category"
      path: "/$category"
      fullPath: "/blog/$category"
      preLoaderRoute: typeof BlogCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
    "/blog/$category/$slug": {
      id: "/blog/$category/$slug"
      path: "/$slug"
      fullPath: "/blog/$category/$slug"
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogCategoryRoute
    }
  }
}

interface BlogCategoryRouteChildren {
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
}

const BlogCategoryRouteChildren: BlogCategoryRouteChildren = {
  BlogCategorySlugRoute: BlogCategorySlugRoute,
}

const BlogCategoryRouteWithChildren = BlogCategoryRoute._addFileChildren(
  BlogCategoryRouteChildren,
)

interface BlogRouteChildren {
  BlogCategoryRoute: typeof BlogCategoryRouteWithChildren
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogCategoryRoute: BlogCategoryRouteWithChildren,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
